#!/usr/bin/env bash
# info about domains

check () {
	if [[ $1 -le 0 || $1 -gt 2 ]]; then
		return 0
	elif [ $1 -eq 1 ]; then
		return 1
	elif [ $1 -eq 2 ]; then
		return 2
	fi
}
printing () {
	local RecordType=$(dig $1 | grep -A1 "ANSWER SECTION:" | awk 'NR==2 {print $4}')
	local destination=$(dig $1 | grep -A1 "ANSWER SECTION:" | awk 'NR==2 {print $5}')
	echo "The subdomain $2 is a $RecordType record and points to $destination"
}

declare -a domains=(
[0]="www"
[1]="lb-01"
[2]="web-01"
[3]="web-02"
)
res=($check $#)
if [ $res -eq 1 ]; then
	for i in "${domains[@]}"; do
		str="$i.$1"
		echo "$(printing "$str" "$i")"
	done
elif [ $res -eq 2 ]; then
	echo "$(printing "$2.$1" "$2")"
fi
