#!/usr/bin/env bash
# nginx
sudo apt upgrade
sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
