#!/usr/bin/env bash
# redirection
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '64i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n'  /etc/nginx/sites-available/default
sudo service nginx restart
