#!/usr/bin/env bash
# load balancing
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '64i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n'  /etc/nginx/sites-available/default
sudo sed -i '40i\\n\tadd_header X-My-Header "$HOSTNAME";\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '67i\\n\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default
sudo service nginx restart
