#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy=2.9.\*
sudo sed -i '$a\\n\nfrontend bukhadra\n\tbind 0:80\n\tdefault_backend web_servers' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 434997-web-01 54.90.62.95\n\tserver 434997-web-02 54.90.37.231' /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
