#!/usr/bin/env bash
# alot of things

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
for (( i=1; i>0; i++));
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM
done
